version: 2.0.{build}
image: Visual Studio 2015
configuration: Debug
platform: x86
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: XRayBuilderGUI.sln
  verbosity: detailed